apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config
  namespace: f1-platform

data:
  PORT: "5001"
  MONGO_URI: "mongodb://mongodb:27017/f1_auth"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  INSTANCE_NAME: "auth-1"