apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
  namespace: f1-platform

data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MONGO_URI: "mongodb://mongodb:27017/f1_driver"
  JOB_SERVICE_URL: "http://job-service:5003"
