name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write
  
jobs:
  gateway:
    name: Gateway CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gateway

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: gateway/package-lock.json

      - name: Install dependencies
        run: npm ci


  auth-service:
    name: Auth Service CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: services/auth-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      

  driver-service:
    name: Driver Service CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/driver-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: services/driver-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      

  job-service:
    name: Job Service CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/job-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: services/job-service/package-lock.json

      - name: Install dependencies
        run: npm ci

  docker-build:
      name: Docker Build & Push
      runs-on: ubuntu-latest

      needs:
        - gateway
        - auth-service
        - driver-service
        - job-service

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Log in to GHCR
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Gateway
          uses: docker/build-push-action@v6
          with:
            context: ./gateway
            push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            tags: |
              ghcr.io/${{ github.repository_owner }}/f1-platform-gateway:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/f1-platform-gateway:latest

        - name: Build and push Auth Service
          uses: docker/build-push-action@v6
          with:
            context: ./services/auth-service
            push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            tags: |
              ghcr.io/${{ github.repository_owner }}/f1-platform-auth-service:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/f1-platform-auth-service:latest

        - name: Build and push Driver Service
          uses: docker/build-push-action@v6
          with:
            context: ./services/driver-service
            push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            tags: |
              ghcr.io/${{ github.repository_owner }}/f1-platform-driver-service:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/f1-platform-driver-service:latest

        - name: Build and push Job Service
          uses: docker/build-push-action@v6
          with:
            context: ./services/job-service
            push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            tags: |
              ghcr.io/${{ github.repository_owner }}/f1-platform-job-service:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/f1-platform-job-service:latest
            